# Generated by Django 3.2.13 on 2022-10-10 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='galnode',
            name='left_character_show',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='galnode',
            name='right_character_show',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
